export const BLOCK_TYPE_START = 'BLOCK_TYPE_START';
export const BLOCK_TYPE_QUESTION = 'BLOCK_TYPE_QUESTION';
export const BLOCK_TYPE_VARIANT = 'BLOCK_TYPE_VARIANT';
export const BLOCK_TYPE_ANSWER = 'BLOCK_TYPE_ANSWER';

export const BLOCK_TYPES = [
    BLOCK_TYPE_START,
    BLOCK_TYPE_QUESTION,
    BLOCK_TYPE_VARIANT,
    BLOCK_TYPE_ANSWER
];